"""
Markdown report formatter for scan results.
Used by the /api/scans/{id}/report?fmt=markdown endpoint.
"""

from datetime import datetime
from typing import Dict, List, Any


SEV_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
SEV_BADGE = {
    "critical": "🔴 CRITICAL",
    "high": "🟠 HIGH",
    "medium": "🟡 MEDIUM",
    "low": "🟢 LOW",
    "info": "⚪ INFO",
}


def to_markdown(scan: Dict[str, Any], findings: List[Dict[str, Any]]) -> str:
    lines = []
    lines.append(f"# Syntrix Scan Report\n")
    lines.append(f"**Target:** `{scan['target']}`")
    lines.append(f"**Scan type:** {scan['scan_type']} · {scan['depth']}")
    lines.append(f"**Submitted:** {scan['submitted_at']}")
    lines.append(f"**Completed:** {scan.get('completed_at', '—')}")
    lines.append(f"**Risk score:** **{scan['risk_score']}/100** · Tier **{scan['risk_tier']}**")
    lines.append("")

    # Summary
    summary = {"critical": 0, "high": 0, "medium": 0, "low": 0, "info": 0}
    for f in findings:
        s = f.get("severity", "info").lower()
        if s in summary:
            summary[s] += 1

    lines.append("## Summary\n")
    lines.append("| Severity | Count |")
    lines.append("|---|---|")
    for k in ["critical", "high", "medium", "low", "info"]:
        lines.append(f"| {SEV_BADGE[k]} | {summary[k]} |")
    lines.append("")

    # Sorted findings
    sorted_findings = sorted(findings, key=lambda f: SEV_ORDER.get(f.get("severity", "info").lower(), 99))

    if not sorted_findings:
        lines.append("## Findings\n\n_No findings._\n")
    else:
        lines.append("## Findings\n")
        for i, f in enumerate(sorted_findings, 1):
            sev = f.get("severity", "info").lower()
            lines.append(f"### {i}. {f.get('title', 'Untitled')}\n")
            lines.append(f"**Severity:** {SEV_BADGE.get(sev, sev.upper())}  ")
            if f.get("cvss"):
                lines.append(f"**CVSS:** {f['cvss']}  ")
            if f.get("owasp"):
                lines.append(f"**OWASP Agentic:** {f['owasp']}  ")
            lines.append(f"**Check ID:** `{f.get('check_id', '—')}`")
            lines.append("")
            lines.append("**Description**")
            lines.append("")
            lines.append(f.get("description", "—"))
            lines.append("")
            lines.append("**Evidence**")
            lines.append("")
            lines.append("```")
            lines.append(str(f.get("evidence", "—"))[:1200])
            lines.append("```")
            lines.append("")
            lines.append("**Remediation**")
            lines.append("")
            lines.append(f.get("remediation", "—"))
            lines.append("")
            lines.append("---")
            lines.append("")

    lines.append("\n_Generated by Syntrix Scanner_")
    return "\n".join(lines)